### ISSUE TITLE
Wrong rendering of emphasis and strong emphasis inlines

### ISSUE THREAD

**Issue by exactamente** [neolithos/NeoMarkdigXaml#2]
According to the CommonMark specification (e.g. the latest one v0.28) "[6.4 Emphasis and strong emphasis](https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis)" the difference between emphasis (rendered in italics) and strong emphasis (rendered in bold) is not only a character but is it single or doubled.

So the single asterisk or the single underscore is *emphasis*, and doubled asterisk or doubled underscore is **strong emphasis**.

But `EmphasisInlineRenderer` in method `WriteSpan` cares only about delimiter character:
```csharp
public class EmphasisInlineRenderer : XamlObjectRenderer<EmphasisInline>
{
	private static bool WriteSpan(XamlMarkdownWriter renderer, EmphasisInline span)
	{
		switch (span.DelimiterChar)
		{
			case '*': // bold
				renderer.WriteStartObject(typeof(Bold));
				return true;
			case '_': // italic
				renderer.WriteStartObject(typeof(Italic));
				return true;
			...
		}
	} // proc WriteSpan
...
}
```

**Comment by neolithos** [comment]
Thx. Do you need an update of the nuget packages?

**Comment by exactamente** [comment]
Yes, please.

**Comment by neolithos** [comment]
Done.
