### ISSUE TITLE
Anchor hyperlinks are routed as "#"

### ISSUE THREAD

**Issue by tim-elmer** [neolithos/NeoMarkdigXaml#6]
When an anchor hyperlink is used such as;
```
[Link to important heading](#important-heading)
...
## Important Heading
```
the parameter `ExecutedRoutedEventArgs.Parameter` is passed to the handling method as `#`, rather than `#important-heading` as expected.

**Comment by neolithos** [comment]
May you check the fix for me?

Do you need a new nuget-package?

**Comment by tim-elmer** [comment]
A new NuGet package would be preferable.

**Comment by neolithos** [comment]
Done. Thx.

**Comment by tim-elmer** [comment]
That's resolved the issue, thank you!
